# 禁止访问 .git、.svn、.hg 目录
location ~* /(\.git|\.svn|\.hg|\.vscode|\.env)/ {
    deny all;
    return 403;
}

# 允许 127.0.0.1 和 特定公网IP 访问 phpinfo.php，其他 IP 被拒绝
location ~* /phpinfo\.php$ {
    allow 127.0.0.1;
    #allow your ip;
    deny all;
    return 403;
}
